language: go

go:
  - "1.12"

services:
  - docker

before_install:
  - docker build --build-arg binary=linux -t telemetry .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master