language: go

go:
  - "1.12"

services:
  - docker
install:
  - pip install --user awscli

jobs:
  include:
    - stage: build & push master
      if: branch = master 
      script:
      - docker build --build-arg binary=linux -t telemetry .
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - docker tag telemetry:latest ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/service-telemetry:${TRAVIS_COMMIT}
      - docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/service-telemetry:${TRAVIS_COMMIT}
    - stage: build & push tag
      if: tag =~ ^v(\d+.?)+.*$
      script:
      - docker build --build-arg binary=linux -t telemetry .
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - docker tag telemetry:latest ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/service-telemetry:${TRAVIS_TAG}
      - docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/service-telemetry:${TRAVIS_TAG}
