language: go

go:
  - "1.12"

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build --build-arg binary=linux -t telemetry .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag telemetry:latest docker.io/nagypeter/telemetry:latest
      - docker push docker.io/nagypeter/telemetry:latest 